// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVhQodJUeF6GmNAVNmXFA6P2CGmDkyRa4',
    appId: '1:793918615718:android:64969ec73f817bd9ee4467',
    messagingSenderId: '793918615718',
    projectId: 'offside-bb10d',
    storageBucket: 'offside-bb10d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWU5jgwsR0PqV5QHvvn2NrZdyYtsRqjkQ',
    appId: '1:793918615718:ios:6c96328ab5afb649ee4467',
    messagingSenderId: '793918615718',
    projectId: 'offside-bb10d',
    storageBucket: 'offside-bb10d.appspot.com',
    iosBundleId: 'pl.shakeit.offside',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWU5jgwsR0PqV5QHvvn2NrZdyYtsRqjkQ',
    appId: '1:793918615718:ios:31195ab3d4f0f531ee4467',
    messagingSenderId: '793918615718',
    projectId: 'offside-bb10d',
    storageBucket: 'offside-bb10d.appspot.com',
    iosBundleId: 'pl.shakeit.offside.RunnerTests',
  );
}
